## Step 1: Load CSV Dataset

In [59]:
import pandas as pd

In [60]:
df = pd.read_csv('Combined_dataset.csv')
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

## Step 2: Explore Dataset

In [61]:
# first 5 rows 
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [62]:
# we can get any number of rows from first
df.head(10)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,NaN,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",NaN,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
6,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
8,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Super King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
9,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets

In [63]:
# prints complete file
#df.to_string()

In [64]:
# get last 5 rows
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [65]:
# get random sample
print('Get any random row from sample')
df.sample()

Get any random row from sample

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
740,20712132,Trendyol,Women Purple Acrylic Pullover Sweater,4.4,5,3599,10.0,"""₹3,599.00""",INR,http://assets.myntassets.com/assets/images/207...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",sweaters

In [66]:
# get dataset info 
# colname,datatype,not null count
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

In [67]:
# number of rows and columns seperately
print(f'Number of rows: {df.shape[0]}')
print(f'Number of columns: {df.shape[1]}')

Number of rows: 1000
Number of columns: 24

In [68]:
# getting attributes of dataset
print('Shape of dataset:')
print(df.shape)
print('Names of all comlumns are:')
print(df.columns)
print('Datatypes of the dataset are:')
print(df.dtypes)
print('Index of attributes:')
print(df.index)

Shape of dataset:
(1000, 24)
Names of all comlumns are:
Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')
Datatypes of the dataset are:
product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object
Index of attributes:
RangeIndex(start=0, stop=1000, step=1)

## Step 3 : Handle Missing Values

#### (i) Getting missing values

In [69]:
print('Missing values in the dataset are')
print(df.isnull().sum())

Missing values in the dataset are
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [70]:
print('Only those Columns having missing values:')
missing = df.isnull().sum()
missing_df = pd.DataFrame({
    'Missing Count': missing
})
print(missing_df[missing_df['Missing Count']>0])

print('Total missing values are:')
print(df.isnull().sum().sum())

Only those Columns having missing values:
                     Missing Count
discount                       121
what_customers_said            573
seller_name                    301
videos                         781
seller_information             301
variations                     562
Total missing values are:
2639

#### (ii) Handling missing values

In [71]:
for col in [
    'discount',
    'what_customers_said',
    'seller_name',
    'videos',
    'seller_information',
    'variations'
]:
    print("\n", col)
    print(df[col].dtype)
    print(df[col].dropna().head())

 discount
float64
0    58.0
1    35.0
2    65.0
3    52.0
4    17.0
Name: discount, dtype: float64

 what_customers_said
object
23    [{"percentage":"100","value_name":"Fit, Just R...
42    [{"percentage":"100","value_name":"Fit, Just R...
46    [{"percentage":"40","value_name":"Fit, A Littl...
48    [{"percentage":"100","value_name":"Fit, Just R...
51    [{"percentage":"70","value_name":"Fit, Just Ri...
Name: what_customers_said, dtype: object

 seller_name
object
5     H &███Hen███ & █████████eta█████████████████████
11                                      Sig███Ove███as
12                Bel███Cas███ash█████████ail█████████
18                   Kas███r L███her█████████Pvt██████
19          PVH███VIN███ASH█████████TE ███████████████
Name: seller_name, dtype: object

 videos
object
0                                 ["rw-8376765_cae700"]
1                                 ["rw-9136281_cae700"]
2     ["https://videos.myntassets.com/assets/videos/...
3     ["https://videos.myntassets.com/assets/videos/...
40                               ["rw-18100576_cae700"]
Name: videos, dtype: object

 seller_information
object
5     Pra███yat███fra█████████PVT███████████████████...
11    Old███. 2███162█████████o. ███████████████████...
12    E-1███103███PIP█████████ IN███████████████████...
18     A-5███ADA███R V█████████ De█████████████████████
19    PVH███vin███ash█████████tdN███████████████████...
Name: seller_information, dtype: object

 variations
object
0                                           [{}]
1                                        [{},{}]
2                            [{},{},{},{},{},{}]
4    [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
5                                        [{},{}]
Name: variations, dtype: object

#### Data Cleaning Strategy

Each column was handled based on its domain meaning,
not generic rules:

- discount → 0 (absence of discount is not average discount)
- JSON columns → '[]' (maintains structural consistency)  
- seller_name → 'Unknown Seller' + missing flag (avoids false attribution)
- seller_information → 'Not Available' (human readable)

Generic approaches like mode/median were intentionally 
avoided where domain logic suggested otherwise.

In [72]:
# Discount
df['discount'] = df['discount'].fillna(0)

# Customer data
df['what_customers_said'] = df['what_customers_said'].fillna('[]')

# Seller name
df['seller_name'] = df['seller_name'].fillna('Unknown Seller')

# Videos
df['videos'] = df['videos'].fillna('[]')

# Seller_information
df['seller_information'] = df['seller_information'].fillna('Unknown Seller')

# variations
df['variations'] = df['variations'].fillna('[]')

In [73]:
# After cleaning missing values 
print(df.isnull().sum())
print(f'Total missing values are: {df.isnull().sum().sum()}')

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64
Total missing values are: 0

In [74]:
for col in [
    'discount',
    'what_customers_said',
    'seller_name',
    'videos',
    'seller_information',
    'variations'
]:
    print(f"\n--- {col} ---")
    print(df[col].head())

--- discount ---
0    58.0
1    35.0
2    65.0
3    52.0
4    17.0
Name: discount, dtype: float64

--- what_customers_said ---
0    []
1    []
2    []
3    []
4    []
Name: what_customers_said, dtype: object

--- seller_name ---
0    Unknown Seller
1    Unknown Seller
2    Unknown Seller
3    Unknown Seller
4    Unknown Seller
Name: seller_name, dtype: object

--- videos ---
0                                ["rw-8376765_cae700"]
1                                ["rw-9136281_cae700"]
2    ["https://videos.myntassets.com/assets/videos/...
3    ["https://videos.myntassets.com/assets/videos/...
4                                                   []
Name: videos, dtype: object

--- seller_information ---
0    Unknown Seller
1    Unknown Seller
2    Unknown Seller
3    Unknown Seller
4    Unknown Seller
Name: seller_information, dtype: object

--- variations ---
0                                           [{}]
1                                        [{},{}]
2                            [{},{},{},{},{},{}]
3                                             []
4    [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
Name: variations, dtype: object

## Step 4 : Basic Operations

In [75]:
df.columns.tolist()

['product_id',
 'title',
 'product_description',
 'rating',
 'ratings_count',
 'initial_price',
 'discount',
 'final_price',
 'currency',
 'images',
 'delivery_options',
 'product_details',
 'breadcrumbs',
 'product_specifications',
 'amount_of_stars',
 'what_customers_said',
 'seller_name',
 'sizes',
 'videos',
 'seller_information',
 'variations',
 'best_offer',
 'more_offers',
 'category']

In [76]:
# Select Columns

selected_columns = df[
[
    'title',
    'category',
    'rating',
    'ratings_count',
    'initial_price',
    'discount',
    'final_price',
    'seller_name'
]
]
print(selected_columns.head())

            title   category  rating  ratings_count  initial_price  discount  \
0     Lino Perros  backpacks     3.8             15           3995      58.0
1  Tommy Hilfiger  backpacks     4.5             67           2899      35.0
2           Lavie  backpacks     4.4            226           2999      65.0
3          F Gear  backpacks     4.4           1052           1675      52.0
4       MYTRIDENT  bath-robe     4.7             12           2899      17.0

   final_price     seller_name
0  "₹3,995.00"  Unknown Seller
1  "₹2,899.00"  Unknown Seller
2  "₹2,999.00"  Unknown Seller
3  "₹1,675.00"  Unknown Seller
4  "₹2,899.00"  Unknown Seller

In [77]:
# Filter High Rated Product

high_rated_product = df[
    (df['rating']>=4.0)&
    (df['ratings_count']>=10)
]
print(high_rated_product.head())

   product_id           title                         product_description  \
1     9136281  Tommy Hilfiger           Unisex Navy Blue Striped Backpack
2    17633752           Lavie              Aries Women Pink Mini Backpack
3     1376949          F Gear  Unisex Navy & Grey Printed Burner Backpack
4    13939916       MYTRIDENT                    Men Blue Solid Bath Robe
5    17198778             H&M  Beige & Tan Solid Stoneware Soap Dispenser

   rating  ratings_count  initial_price  discount  final_price currency  \
1     4.5             67           2899      35.0  "₹2,899.00"      INR
2     4.4            226           2999      65.0  "₹2,999.00"      INR
3     4.4           1052           1675      52.0  "₹1,675.00"      INR
4     4.7             12           2899      17.0  "₹2,899.00"      INR
5     4.5             42           1399       0.0  "₹1,399.00"      INR

                                              images  ...  \
1  http://assets.myntassets.com/assets/images/913...  ...
2  http://assets.myntassets.com/assets/images/176...  ...
3  http://assets.myntassets.com/assets/images/137...  ...
4  http://assets.myntassets.com/assets/images/pro...  ...
5  http://assets.myntassets.com/assets/images/171...  ...

                                     amount_of_stars what_customers_said  \
1  {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                  []
2  {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                  []
3  {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                  []
4  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                  []
5  {"1_star":2,"2_stars":2,"3_stars":0,"4_stars":...                  []

                                        seller_name  \
1                                    Unknown Seller
2                                    Unknown Seller
3                                    Unknown Seller
4                                    Unknown Seller
5  H &███Hen███ & █████████eta█████████████████████

                                               sizes  \
1                               [{"size":"Onesize"}]
2                                     [{"size":"S"}]
3                               [{"size":"Onesize"}]
4  [{"size":"M","value":"45.0in","value_name":"Fr...
5                               [{"size":"Onesize"}]

                                              videos  \
1                              ["rw-9136281_cae700"]
2  ["https://videos.myntassets.com/assets/videos/...
3  ["https://videos.myntassets.com/assets/videos/...
4                                                 []
5                                                 []

                                  seller_information  \
1                                     Unknown Seller
2                                     Unknown Seller
3                                     Unknown Seller
4                                     Unknown Seller
5  Pra███yat███fra█████████PVT███████████████████...

                                    variations  \
1                                      [{},{}]
2                          [{},{},{},{},{},{}]
3                                           []
4  [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
5                                      [{},{}]

                                          best_offer  \
1                                                 {}
2                                                 {}
3                                                 {}
4                                                 {}
5  {"applicable_on":"Orders above Rs. 1499 (only ...

                                         more_offers              category
1  [{"offer_name":"10% Instant Discount on Citi C...             backpacks
2  [{"offer_name":"10% Instant Discount on Citi C...             backpacks
3  [{"offer_name":"10% Instant Discount on Citi C...             backpacks
4  [{"offer_name":"10% Instant Discount on IndusI...             bath-robe
5  [{"offer_name":"10% Instant Discount on IndusI...  bathroom-accessories

[5 rows x 24 columns]

In [78]:
# Filter high dicount products

high_discount_product = df[
    df['discount']>50
]
print(high_discount_product.head())

   product_id        title                                product_description  \
0     8376765  Lino Perros                     Women Navy Blue Solid Backpack
2    17633752        Lavie                     Aries Women Pink Mini Backpack
3     1376949       F Gear         Unisex Navy & Grey Printed Burner Backpack
6    19851824   AVI Living          Grey Solid 500 GSM Pure Cotton Bath Towel
7    18602872      My Room  Yellow & Green Floral 140 TC King Bedsheet wit...

   rating  ratings_count  initial_price  discount  final_price currency  \
0     3.8             15           3995      58.0  "₹3,995.00"      INR
2     4.4            226           2999      65.0  "₹2,999.00"      INR
3     4.4           1052           1675      52.0  "₹1,675.00"      INR
6     4.0              5           1399      65.0  "₹1,399.00"      INR
7     4.7             10           2999      54.0  "₹2,999.00"      INR

                                              images  ...  \
0  http://assets.myntassets.com/assets/images/837...  ...
2  http://assets.myntassets.com/assets/images/176...  ...
3  http://assets.myntassets.com/assets/images/137...  ...
6  http://assets.myntassets.com/assets/images/198...  ...
7  http://assets.myntassets.com/assets/images/186...  ...

                                     amount_of_stars what_customers_said  \
0  {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                  []
2  {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                  []
3  {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                  []
6  {"1_star":0,"2_stars":1,"3_stars":0,"4_stars":...                  []
7  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                  []

      seller_name                                              sizes  \
0  Unknown Seller                               [{"size":"Onesize"}]
2  Unknown Seller                                     [{"size":"S"}]
3  Unknown Seller                               [{"size":"Onesize"}]
6  Unknown Seller                               [{"size":"Onesize"}]
7  Unknown Seller  [{"size":"Single"},{"size":"Double Queen"},{"s...

                                              videos seller_information  \
0                              ["rw-8376765_cae700"]     Unknown Seller
2  ["https://videos.myntassets.com/assets/videos/...     Unknown Seller
3  ["https://videos.myntassets.com/assets/videos/...     Unknown Seller
6                                                 []     Unknown Seller
7                                                 []     Unknown Seller

            variations best_offer  \
0                 [{}]         {}
2  [{},{},{},{},{},{}]         {}
3                   []         {}
6              [{},{}]         {}
7                 [{}]         {}

                                         more_offers     category
0  [{"offer_name":"10% Instant Discount on Citi C...    backpacks
2  [{"offer_name":"10% Instant Discount on Citi C...    backpacks
3  [{"offer_name":"10% Instant Discount on Citi C...    backpacks
6  [{"offer_name":"10% Instant Discount on Citi C...  bath-towels
7  [{"offer_name":"10% Instant Discount on Citi C...    bedsheets

[5 rows x 24 columns]

In [79]:
# best deals

best_deals = df[
    (df['rating']>=4.0)&
    (df['discount']>=30)
]
print(best_deals.head())

   product_id           title  \
1     9136281  Tommy Hilfiger
2    17633752           Lavie
3     1376949          F Gear
6    19851824      AVI Living
7    18602872         My Room

                                 product_description  rating  ratings_count  \
1                  Unisex Navy Blue Striped Backpack     4.5             67
2                     Aries Women Pink Mini Backpack     4.4            226
3         Unisex Navy & Grey Printed Burner Backpack     4.4           1052
6          Grey Solid 500 GSM Pure Cotton Bath Towel     4.0              5
7  Yellow & Green Floral 140 TC King Bedsheet wit...     4.7             10

   initial_price  discount  final_price currency  \
1           2899      35.0  "₹2,899.00"      INR
2           2999      65.0  "₹2,999.00"      INR
3           1675      52.0  "₹1,675.00"      INR
6           1399      65.0  "₹1,399.00"      INR
7           2999      54.0  "₹2,999.00"      INR

                                              images  ...  \
1  http://assets.myntassets.com/assets/images/913...  ...
2  http://assets.myntassets.com/assets/images/176...  ...
3  http://assets.myntassets.com/assets/images/137...  ...
6  http://assets.myntassets.com/assets/images/198...  ...
7  http://assets.myntassets.com/assets/images/186...  ...

                                     amount_of_stars what_customers_said  \
1  {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                  []
2  {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                  []
3  {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                  []
6  {"1_star":0,"2_stars":1,"3_stars":0,"4_stars":...                  []
7  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                  []

      seller_name                                              sizes  \
1  Unknown Seller                               [{"size":"Onesize"}]
2  Unknown Seller                                     [{"size":"S"}]
3  Unknown Seller                               [{"size":"Onesize"}]
6  Unknown Seller                               [{"size":"Onesize"}]
7  Unknown Seller  [{"size":"Single"},{"size":"Double Queen"},{"s...

                                              videos seller_information  \
1                              ["rw-9136281_cae700"]     Unknown Seller
2  ["https://videos.myntassets.com/assets/videos/...     Unknown Seller
3  ["https://videos.myntassets.com/assets/videos/...     Unknown Seller
6                                                 []     Unknown Seller
7                                                 []     Unknown Seller

            variations best_offer  \
1              [{},{}]         {}
2  [{},{},{},{},{},{}]         {}
3                   []         {}
6              [{},{}]         {}
7                 [{}]         {}

                                         more_offers     category
1  [{"offer_name":"10% Instant Discount on Citi C...    backpacks
2  [{"offer_name":"10% Instant Discount on Citi C...    backpacks
3  [{"offer_name":"10% Instant Discount on Citi C...    backpacks
6  [{"offer_name":"10% Instant Discount on Citi C...  bath-towels
7  [{"offer_name":"10% Instant Discount on Citi C...    bedsheets

[5 rows x 24 columns]

## Step 5 : Remove Duplicates

In [80]:
print('Number of duplicate rows')
print(df.duplicated().sum())

print("Product ID duplicates:", df['product_id'].duplicated().sum())

Number of duplicate rows
0
Product ID duplicates: 0

In [81]:
# To remove duplicates
df.drop_duplicates(inplace=True)
# if there is same order multiple times
df = df.drop_duplicates(
    subset='product_id',
    keep='first'
)

## Step 6 : Create Derived Column

In [82]:
df['final_price'].unique()

array(['"₹3,995.00"', '"₹2,899.00"', '"₹2,999.00"', '"₹1,675.00"',
       '"₹1,399.00"', '"₹2,199.00"', '"₹865.00"', '"₹404.00"',
       '"₹3,499.00"', '"₹1,599.00"', '"₹1,199.00"', '"₹2,599.00"',
       '"₹6,329.00"', '"₹223.00"', '"₹1,799.00"', '"₹699.00"',
       '"₹1,087.00"', '"₹3,839.00"', '"₹367.00"', '"₹579.00"',
       '"₹299.00"', '"₹374.00"', '"₹499.00"', '"₹398.00"', '"₹604.00"',
       '"₹2,249.00"', '"₹449.00"', '"₹345.00"', '"₹2,547.00"',
       '"₹649.00"', '"₹995.00"', '"₹384.00"', '"₹815.00"', '"₹305.00"',
       '"₹1,499.00"', '"₹298.00"', '"₹215.00"', '"₹370.00"', '"₹539.00"',
       '"₹395.00"', '"₹379.00"', '"₹399.00"', '"₹249.00"', '"₹310.00"',
       '"₹230.00"', '"₹265.00"', '"₹714.00"', '"₹1,699.00"',
       '"₹7,799.00"', '"₹771.00"', '"₹3,224.00"', '"₹569.00"',
       '"₹1,678.00"', '"₹899.00"', '"₹799.00"', '"₹1,649.00"',
       '"₹3,599.00"', '"₹999.00"', '"₹1,299.00"', '"₹4,999.00"',
       '"₹599.00"', '"₹659.00"', '"₹6,999.00"', '"₹7,149.00"',
       '"₹4,479.00"', '"₹3,749.00"', '"₹1,394.00"', '"₹4,199.00"',
       '"₹935.00"', '"₹719.00"', '"₹314.00"', '"₹1,980.00"',
       '"₹1,700.00"', '"₹1,750.00"', '"₹359.00"', '"₹2,419.00"',
       '"₹2,094.00"', '"₹2,519.00"', '"₹628.00"', '"₹4,130.00"',
       '"₹1,540.00"', '"₹3,150.00"', '"₹2,450.00"', '"₹335.00"',
       '"₹1,247.00"', '"₹471.00"', '"₹884.00"', '"₹3,757.00"',
       '"₹2,399.00"', '"₹597.00"', '"₹849.00"', '"₹2,799.00"',
       '"₹1,119.00"', '"₹1,999.00"', '"₹679.00"', '"₹475.00"',
       '"₹940.00"', '"₹987.00"', '"₹809.00"', '"₹892.00"', '"₹753.00"',
       '"₹340.00"', '"₹495.00"', '"₹437.00"', '"₹279.00"', '"₹749.00"',
       '"₹605.00"', '"₹2,804.00"', '"₹1,476.00"', '"₹3,120.00"',
       '"₹4,830.00"', '"₹927.00"', '"₹756.00"', '"₹769.00"', '"₹869.00"',
       '"₹2,559.00"', '"₹507.00"', '"₹640.00"', '"₹1,960.00"',
       '"₹5,699.00"', '"₹1,319.00"', '"₹689.00"', '"₹1,475.00"',
       '"₹703.00"', '"₹329.00"', '"₹524.00"', '"₹2,499.00"',
       '"₹1,495.00"', '"₹989.00"', '"₹1,349.00"', '"₹1,899.00"',
       '"₹743.00"', '"₹681.00"', '"₹322.00"', '"₹1,046.00"', '"₹643.00"',
       '"₹1,224.00"', '"₹669.00"', '"₹1,149.00"', '"₹1,329.00"',
       '"₹1,371.00"', '"₹350.00"', '"₹755.00"', '"₹1,429.00"',
       '"₹1,363.00"', '"₹818.00"', '"₹227.00"', '"₹355.00"', '"₹639.00"',
       '"₹2,079.00"', '"₹947.00"', '"₹487.00"', '"₹419.00"', '"₹500.00"',
       '"₹423.00"', '"₹307.00"', '"₹433.00"', '"₹1,995.00"', '"₹425.00"',
       '"₹2,039.00"', '"₹349.00"', '"₹872.00"', '"₹696.00"', '"₹346.00"',
       '"₹542.00"', '"₹313.00"', '"₹483.00"', '"₹480.00"', '"₹2,837.00"',
       '"₹446.00"', '"₹389.00"', '"₹839.00"', '"₹2,645.00"',
       '"₹1,484.00"', '"₹2,319.00"', '"₹629.00"', '"₹593.00"',
       '"₹1,380.00"', '"₹853.00"', '"₹1,420.00"', '"₹1,591.00"',
       '"₹1,037.00"', '"₹974.00"', '"₹2,349.00"', '"₹1,059.00"',
       '"₹787.00"', '"₹840.00"', '"₹280.00"', '"₹676.00"', '"₹426.00"',
       '"₹959.00"', '"₹4,990.00"', '"₹6,990.00"', '"₹9,490.00"',
       '"₹2,299.00"', '"₹783.00"', '"₹1,559.00"', '"₹259.00"',
       '"₹199.00"', '"₹798.00"', '"₹973.00"', '"₹554.00"', '"₹439.00"',
       '"₹1,459.00"', '"₹4,079.00"', '"₹2,958.00"', '"₹5,999.00"',
       '"₹1,385.00"', '"₹6,899.00"', '"₹1,194.00"', '"₹3,145.00"',
       '"₹2,078.00"', '"₹479.00"', '"₹440.00"', '"₹219.00"', '"₹796.00"',
       '"₹1,039.00"', '"₹1,648.00"', '"₹924.00"', '"₹4,495.00"',
       '"₹3,495.00"', '"₹3,099.00"', '"₹3,999.00"', '"₹1,290.00"',
       '"₹845.00"', '"₹1,679.00"', '"₹1,139.00"', '"₹9,999.00"',
       '"₹3,199.00"', '"₹735.00"', '"₹1,479.00"', '"₹2,690.00"',
       '"₹1,079.00"', '"₹595.00"', '"₹978.00"', '"₹532.00"',
       '"₹2,624.00"', '"₹1,424.00"', '"₹2,960.00"', '"₹1,090.00"',
       '"₹1,511.00"', '"₹3,149.00"', '"₹2,759.00"', '"₹1,578.00"',
       '"₹4,549.00"', '"₹509.00"', '"₹1,439.00"', '"₹1,849.00"',
       '"₹2,649.00"', '"₹3,249.00"', '"₹2,749.00"', '"₹3,299.00"',
       '"₹2,699.00"', '"₹3,134.00"', '"₹4,099.00"', '"₹2,287.00"',
       '"₹4,799.00"', '"₹1,891.00"', '"₹854.00"', '"₹1,709.00"',
       '"₹4,399.00"', '"₹671.00"', '"₹1,749.00"', '"₹2,449.00"',
       '"₹4,699.00"', '"₹607.00"', '"₹1,169.00"', '"₹682.00"',
       '"₹1,979.00"', '"₹1,052.00"', '"₹1,647.00"', '"₹1,359.00"',
       '"₹739.00"', '"₹2,155.00"', '"₹1,362.00"', '"₹863.00"',
       '"₹767.00"', '"₹2,024.00"', '"₹2,027.00"', '"₹1,249.00"',
       '"₹1,633.00"', '"₹2,089.00"', '"₹692.00"', '"₹1,500.00"',
       '"₹1,345.00"', '"₹377.00"', '"₹5,199.00"', '"₹5,995.00"',
       '"₹400.00"', '"₹545.00"', '"₹2,900.00"', '"₹874.00"',
       '"₹1,403.00"', '"₹1,124.00"', '"₹747.00"', '"₹1,109.00"',
       '"₹737.00"', '"₹1,680.00"', '"₹2,342.00"', '"₹3,399.00"',
       '"₹2,997.00"', '"₹434.00"', '"₹1,049.00"', '"₹489.00"',
       '"₹664.00"', '"₹559.00"', '"₹2,099.00"', '"₹402.00"', '"₹225.00"',
       '"₹740.00"', '"₹983.00"', '"₹494.00"', '"₹557.00"', '"₹493.00"',
       '"₹552.00"', '"₹450.00"', '"₹864.00"', '"₹415.00"', '"₹2,250.00"',
       '"₹1,824.00"', '"₹693.00"', '"₹424.00"', '"₹2,636.00"',
       '"₹1,549.00"', '"₹1,813.00"', '"₹2,197.00"', '"₹4,125.00"',
       '"₹1,007.00"', '"₹1,103.00"', '"₹1,781.00"', '"₹1,271.00"',
       '"₹1,024.00"', '"₹1,147.00"', '"₹1,343.00"', '"₹247.00"',
       '"₹284.00"', '"₹1,250.00"', '"₹285.00"', '"₹4,977.00"',
       '"₹4,691.00"', '"₹6,317.00"', '"₹7,547.00"', '"₹5,291.00"',
       '"₹454.00"', '"₹1,259.00"', '"₹701.00"', '"₹741.00"',
       '"₹1,624.00"', '"₹491.00"', '"₹519.00"', '"₹512.00"',
       '"₹1,539.00"', '"₹1,924.00"', '"₹549.00"', '"₹474.00"',
       '"₹730.00"', '"₹1,847.00"', '"₹591.00"', '"₹1,151.00"',
       '"₹540.00"', '"₹584.00"', '"₹687.00"', '"₹369.00"', '"₹776.00"',
       '"₹911.00"', '"₹4,299.00"', '"₹1,795.00"', '"₹650.00"',
       '"₹321.00"', '"₹1,017.00"', '"₹1,874.00"', '"₹979.00"',
       '"₹645.00"', '"₹624.00"', '"₹568.00"', '"₹363.00"', '"₹751.00"',
       '"₹944.00"', '"₹2,794.00"', '"₹7,199.00"', '"₹2,339.00"',
       '"₹4,599.00"', '"₹2,879.00"', '"₹1,091.00"', '"₹5,299.00"',
       '"₹13,499.00"', '"₹2,695.00"', '"₹6,490.00"', '"₹5,490.00"',
       '"₹12,999.00"', '"₹11,999.00"', '"₹4,049.00"', '"₹4,499.00"',
       '"₹5,499.00"', '"₹10,199.00"', '"₹2,469.00"', '"₹3,119.00"',
       '"₹5,599.00"', '"₹3,899.00"', '"₹14,249.00"', '"₹1,053.00"',
       '"₹2,474.00"', '"₹909.00"', '"₹3,480.00"', '"₹511.00"',
       '"₹2,590.00"', '"₹2,080.00"', '"₹759.00"', '"₹758.00"',
       '"₹1,187.00"', '"₹3,359.00"', '"₹615.00"', '"₹606.00"',
       '"₹732.00"', '"₹431.00"', '"₹594.00"', '"₹1,133.00"',
       '"₹1,889.00"', '"₹1,590.00"', '"₹3,200.00"', '"₹567.00"',
       '"₹1,800.00"', '"₹328.00"', '"₹558.00"', '"₹1,998.00"',
       '"₹1,990.00"', '"₹1,839.00"', '"₹600.00"', '"₹1,099.00"',
       '"₹895.00"', '"₹3,490.00"', '"₹1,975.00"', '"₹2,490.00"',
       '"₹3,590.00"', '"₹619.00"', '"₹2,390.00"', '"₹2,990.00"',
       '"₹2,495.00"', '"₹631.00"', '"₹17,995.00"', '"₹582.00"',
       '"₹1,029.00"', '"₹529.00"', '"₹257.00"', '"₹625.00"', '"₹674.00"',
       '"₹578.00"', '"₹1,229.00"', '"₹293.00"', '"₹835.00"', '"₹506.00"',
       '"₹636.00"', '"₹683.00"', '"₹560.00"', '"₹2,595.00"',
       '"₹1,050.00"', '"₹4,997.00"', '"₹10,416.00"', '"₹1,596.00"',
       '"₹6,250.00"', '"₹9,709.00"', '"₹3,266.00"', '"₹3,235.00"',
       '"₹11,890.00"', '"₹8,900.00"', '"₹7,950.00"'], dtype=object)

In [83]:
# Creating col quantity
df['quantity'] = 1

# Final price(in float)
price = (
    df['final_price']
    .str.replace('"', '', regex=False)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
    .astype(float)
)

#total amount
df['total_amount'] = price * df['quantity'] 
print(df.head())

# Checking if there are any null values
print('Null values are:')
print(df.isnull().sum().sum())

   product_id           title                         product_description  \
0     8376765     Lino Perros              Women Navy Blue Solid Backpack
1     9136281  Tommy Hilfiger           Unisex Navy Blue Striped Backpack
2    17633752           Lavie              Aries Women Pink Mini Backpack
3     1376949          F Gear  Unisex Navy & Grey Printed Burner Backpack
4    13939916       MYTRIDENT                    Men Blue Solid Bath Robe

   rating  ratings_count  initial_price  discount  final_price currency  \
0     3.8             15           3995      58.0  "₹3,995.00"      INR
1     4.5             67           2899      35.0  "₹2,899.00"      INR
2     4.4            226           2999      65.0  "₹2,999.00"      INR
3     4.4           1052           1675      52.0  "₹1,675.00"      INR
4     4.7             12           2899      17.0  "₹2,899.00"      INR

                                              images  ...     seller_name  \
0  http://assets.myntassets.com/assets/images/837...  ...  Unknown Seller
1  http://assets.myntassets.com/assets/images/913...  ...  Unknown Seller
2  http://assets.myntassets.com/assets/images/176...  ...  Unknown Seller
3  http://assets.myntassets.com/assets/images/137...  ...  Unknown Seller
4  http://assets.myntassets.com/assets/images/pro...  ...  Unknown Seller

                                               sizes  \
0                               [{"size":"Onesize"}]
1                               [{"size":"Onesize"}]
2                                     [{"size":"S"}]
3                               [{"size":"Onesize"}]
4  [{"size":"M","value":"45.0in","value_name":"Fr...

                                              videos seller_information  \
0                              ["rw-8376765_cae700"]     Unknown Seller
1                              ["rw-9136281_cae700"]     Unknown Seller
2  ["https://videos.myntassets.com/assets/videos/...     Unknown Seller
3  ["https://videos.myntassets.com/assets/videos/...     Unknown Seller
4                                                 []     Unknown Seller

                                    variations best_offer  \
0                                         [{}]         {}
1                                      [{},{}]         {}
2                          [{},{},{},{},{},{}]         {}
3                                           []         {}
4  [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]         {}

                                         more_offers   category quantity  \
0  [{"offer_name":"10% Instant Discount on Citi C...  backpacks        1
1  [{"offer_name":"10% Instant Discount on Citi C...  backpacks        1
2  [{"offer_name":"10% Instant Discount on Citi C...  backpacks        1
3  [{"offer_name":"10% Instant Discount on Citi C...  backpacks        1
4  [{"offer_name":"10% Instant Discount on IndusI...  bath-robe        1

  total_amount
0       3995.0
1       2899.0
2       2999.0
3       1675.0
4       2899.0

[5 rows x 26 columns]
Null values are:
0

## Step 7 : Cleaned Dataset

In [84]:
df.to_csv(
    'Cleaned_dataset.csv',
    index = False
)
print('Cleaned Dataset Saved')

Cleaned Dataset Saved